{
 "title": "Metrics AAP",
 "description": "Show Ansible Automation Platform metrics",
 "tags": [
  "Ansible",
  "AAP"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "AAP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(awx_instance_info)", "legendFormat": "Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "awx_license_instance_total", "legendFormat": "Total de Licenças" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(awx_license_instance_total - awx_license_instance_free)"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "awx_users_total", "legendFormat": "Total" },
    {
     "expr": "count(awx_sessions_total{type=\"user\"})",
     "legendFormat": "Users"
    },
    {
     "expr": "count(awx_sessions_total{type=\"anonymous\"})",
     "legendFormat": "Anonymous"
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "License",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"successful\"}",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"dependency\"})",
     "legendFormat": "Dependency"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"manual\"})",
     "legendFormat": "Manual"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"relaunch\"})",
     "legendFormat": "Relaunch"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"scheduled\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"workflow\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 } },
  {
   "title": "Job Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(rate(awx_running_jobs_total[1m] offset 1d))",
     "legendFormat": "Last day"
    },
    { "expr": "awx_running_jobs_total[1d]", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Job Pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(rate(awx_pending_jobs_total[1m] offset 1d))",
     "legendFormat": "Last day"
    },
    { "expr": "awx_pending_jobs_total[1d]", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "awx_job_templates_total", "legendFormat": "Job Templates" },
    { "expr": "awx_inventories_total", "legendFormat": "Inventories" },
    { "expr": "awx_projects_total", "legendFormat": "Projects" },
    { "expr": "awx_organizations_total", "legendFormat": "Organizations" },
    {
     "expr": "awx_hosts_total{type=\"active\"}",
     "legendFormat": "Active Hosts"
    },
    { "expr": "awx_teams_total", "legendFormat": "Teams" },
    {
     "expr": "awx_workflow_job_templates_total",
     "legendFormat": "Workflow  Job Templates"
    }
   ]
  }
 ]
}